using System;
using System.Collections.Generic;
using System.Text;
using SKGPortalCore.Data;
using SKGPortalCore.Model.MasterData;
using SKGPortalCore.Model.MasterData.OperateSystem;
using SKGPortalCore.Model.SourceData;
using SKGPortalCore.Model.System;
using SKGPortalCore.Repository.MasterData;

namespace SKGPortalCore.SeedDataInitial.MasterData
{
    public static class CollectionTypeSeedData
    {
        /// <summary>
        /// 新增「代收類別」-初始資料
        /// </summary>
        /// <param name="db"></param>
        public static void CreateCollectionType(SysMessageLog Message, ApplicationDbContext dataAccess)
        {
            try
            {
                Message.Prefix = "新增「代收類別」-初始資料：";
                using CollectionTypeRepository repo = new CollectionTypeRepository(dataAccess) { User = SystemOperator.SysOperator, Message = Message };
                List<CollectionTypeSet> collectionTypes = new List<CollectionTypeSet>() {
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId=CP.PostCollectionTypeId,CollectionTypeName="郵局特戶", ChargePayType= ChargePayType.Deduction},
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = CP.PostCollectionTypeId, ChannelId = "05", SRange = 1, ERange = 100, ChannelFee = 5, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = CP.PostCollectionTypeId, ChannelId = "05", SRange = 101, ERange = 1000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = CP.PostCollectionTypeId, ChannelId = "05", SRange = 1001, ERange = 9999999, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = CP.PostCollectionTypeId, ChannelId = "A1", SRange = 1, ERange = 100, ChannelFee = 5, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = CP.PostCollectionTypeId, ChannelId = "A1", SRange = 101, ERange = 1000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = CP.PostCollectionTypeId, ChannelId = "A1", SRange = 1001, ERange = 9999999, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 }
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId=CP.PostCollectionTypeId, ChannelId="05", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId=CP.PostCollectionTypeId, ChannelId="A1", PayPeriodType= PayPeriodType.NDay_A },
                                //new CollectionTypeVerifyPeriodModel(){ CollectionTypeId=ConstParameter.PostCollectionTypeId, ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                            },
                         },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="62H",CollectionTypeName="一般代收(2萬、內扣、日結)", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62H", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 12, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62H", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 13, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62H", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 12, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62H", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62H", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62H", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="62I",CollectionTypeName="一般代收(4萬、內扣、日結)", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62I", ChannelId = "02", SRange = 20001, ERange = 40000, ChannelFee = 16, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62I", ChannelId = "03", SRange = 20001, ERange = 40000, ChannelFee = 16, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62I", ChannelId = "04", SRange = 20001, ERange = 40000, ChannelFee = 16, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 }
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62I", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62I", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62I", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="62M",CollectionTypeName="一般代收(6萬、內扣、日結)", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62M", ChannelId = "02", SRange = 40001, ERange = 60000, ChannelFee = 21, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62M", ChannelId = "03", SRange = 40001, ERange = 60000, ChannelFee = 21, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62M", ChannelId = "04", SRange = 40001, ERange = 60000, ChannelFee = 21, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 }
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62M", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62M", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62M", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="62N",CollectionTypeName="一般代收(2萬、外加、日結)", ChargePayType= ChargePayType.Increase },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62N", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 12, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62N", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 13, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62N", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 12, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62N", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62N", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62N", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="62T",CollectionTypeName="一般代收(4萬、外加、日結)", ChargePayType= ChargePayType.Increase },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62T", ChannelId = "02", SRange = 20001, ERange = 40000, ChannelFee = 16, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62T", ChannelId = "03", SRange = 20001, ERange = 40000, ChannelFee = 16, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62T", ChannelId = "04", SRange = 20001, ERange = 40000, ChannelFee = 16, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 }
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62T", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62T", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62T", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="62U",CollectionTypeName="一般代收(6萬、外加、日結)", ChargePayType= ChargePayType.Increase },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62U", ChannelId = "02", SRange = 40001, ERange = 60000, ChannelFee = 21, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62U", ChannelId = "03", SRange = 40001, ERange = 60000, ChannelFee = 21, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62U", ChannelId = "04", SRange = 40001, ERange = 60000, ChannelFee = 21, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 }
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62U", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62U", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62U", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="62V",CollectionTypeName="政黨捐款", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62V", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62V", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62V", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 }
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62V", ChannelId="02", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62V", ChannelId="03", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62V", ChannelId="04", PayPeriodType= PayPeriodType.TenDay },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="62W",CollectionTypeName="慈善捐款", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62W", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62W", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62W", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 }
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62W", ChannelId="02", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62W", ChannelId="03", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62W", ChannelId="04", PayPeriodType= PayPeriodType.TenDay },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="62X",CollectionTypeName="黨費", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62X", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62X", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62X", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 }
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62X", ChannelId="02", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62X", ChannelId="03", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62X", ChannelId="04", PayPeriodType= PayPeriodType.TenDay },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="62Y",CollectionTypeName="有線電視", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62Y", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62Y", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62Y", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 }
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62Y", ChannelId="02", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62Y", ChannelId="03", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62Y", ChannelId="04", PayPeriodType= PayPeriodType.TenDay },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="62Z",CollectionTypeName="瓦斯費", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62Z", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62Z", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "62Z", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 }
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62Z", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62Z", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="62Z", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6RK",CollectionTypeName="超商代收-學雜費", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RK", ChannelId = "01", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RK", ChannelId = "02", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RK", ChannelId = "03", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RK", ChannelId = "04", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RK", ChannelId = "12", SRange = 40001, ERange = 60000, ChannelFee = 6, ChannelFeedBackFee = 12 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RK", ChannelId = "13", SRange = 40001, ERange = 60000, ChannelFee = 0, ChannelFeedBackFee = 0 , ChannelRebateFee = 20 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RK", ChannelId = "14", SRange = 40001, ERange = 60000, ChannelFee = 6, ChannelFeedBackFee = 12 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RK", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RK", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RK", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RK", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RK", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RK", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RK", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6RL",CollectionTypeName="超商代收-學雜費", ChargePayType= ChargePayType.Increase },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RL", ChannelId = "01", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RL", ChannelId = "02", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RL", ChannelId = "03", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RL", ChannelId = "04", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RL", ChannelId = "12", SRange = 40001, ERange = 60000, ChannelFee = 6, ChannelFeedBackFee = 12 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RL", ChannelId = "13", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RL", ChannelId = "14", SRange = 40001, ERange = 60000, ChannelFee = 6, ChannelFeedBackFee = 12 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RL", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RL", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RL", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RL", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RL", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RL", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RL", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6RM",CollectionTypeName="超商代收-一般", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RM", ChannelId = "01", SRange = 40001, ERange = 60000, ChannelFee = 13, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RM", ChannelId = "02", SRange = 40001, ERange = 60000, ChannelFee = 12, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RM", ChannelId = "03", SRange = 40001, ERange = 60000, ChannelFee = 12, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RM", ChannelId = "04", SRange = 40001, ERange = 60000, ChannelFee = 13, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RM", ChannelId = "12", SRange = 40001, ERange = 60000, ChannelFee = 15, ChannelFeedBackFee = 5 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RM", ChannelId = "13", SRange = 40001, ERange = 60000, ChannelFee = 0, ChannelFeedBackFee = 0 , ChannelRebateFee = 20 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RM", ChannelId = "14", SRange = 40001, ERange = 60000, ChannelFee = 8, ChannelFeedBackFee = 12 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RM", ChannelId="01", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RM", ChannelId="02", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RM", ChannelId="03", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RM", ChannelId="04", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RM", ChannelId="12", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RM", ChannelId="13", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RM", ChannelId="14", PayPeriodType= PayPeriodType.TenDay },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6RN",CollectionTypeName="超商代收-一般", ChargePayType= ChargePayType.Increase },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RN", ChannelId = "01", SRange = 40001, ERange = 60000, ChannelFee = 22, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RN", ChannelId = "02", SRange = 40001, ERange = 60000, ChannelFee = 22, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RN", ChannelId = "03", SRange = 40001, ERange = 60000, ChannelFee = 22, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RN", ChannelId = "04", SRange = 40001, ERange = 60000, ChannelFee = 22, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RN", ChannelId = "12", SRange = 40001, ERange = 60000, ChannelFee = 15, ChannelFeedBackFee = 5 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RN", ChannelId = "13", SRange = 40001, ERange = 60000, ChannelFee = 22, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6RN", ChannelId = "14", SRange = 40001, ERange = 60000, ChannelFee = 8, ChannelFeedBackFee = 12 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RN", ChannelId="01", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RN", ChannelId="02", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RN", ChannelId="03", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RN", ChannelId="04", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RN", ChannelId="12", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RN", ChannelId="13", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6RN", ChannelId="14", PayPeriodType= PayPeriodType.TenDay },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6V0",CollectionTypeName="超商代收-學雜費", ChargePayType= ChargePayType.Increase },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V0", ChannelId = "01", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V0", ChannelId = "02", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V0", ChannelId = "03", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V0", ChannelId = "04", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V0", ChannelId = "12", SRange = 20001, ERange = 40000, ChannelFee = 6, ChannelFeedBackFee = 9 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V0", ChannelId = "13", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V0", ChannelId = "14", SRange = 20001, ERange = 40000, ChannelFee = 6, ChannelFeedBackFee = 9 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V0", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V0", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V0", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V0", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V0", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V0", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V0", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6V1",CollectionTypeName="超商代收-一般", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V1", ChannelId = "01", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V1", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V1", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V1", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V1", ChannelId = "12", SRange = 1, ERange = 20000, ChannelFee = 8, ChannelFeedBackFee = 2 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V1", ChannelId = "13", SRange = 1, ERange = 20000, ChannelFee = 0, ChannelFeedBackFee = 0 , ChannelRebateFee = 10 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V1", ChannelId = "14", SRange = 1, ERange = 20000, ChannelFee = 7, ChannelFeedBackFee = 3 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V1", ChannelId="01", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V1", ChannelId="02", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V1", ChannelId="03", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V1", ChannelId="04", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V1", ChannelId="12", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V1", ChannelId="13", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V1", ChannelId="14", PayPeriodType= PayPeriodType.TenDay },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6V2",CollectionTypeName="超商代收-一般", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V2", ChannelId = "01", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V2", ChannelId = "02", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V2", ChannelId = "03", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V2", ChannelId = "04", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V2", ChannelId = "12", SRange = 20001, ERange = 40000, ChannelFee = 12, ChannelFeedBackFee = 3 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V2", ChannelId = "13", SRange = 20001, ERange = 40000, ChannelFee = 0, ChannelFeedBackFee = 0 , ChannelRebateFee = 15 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V2", ChannelId = "14", SRange = 20001, ERange = 40000, ChannelFee = 8, ChannelFeedBackFee = 7 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V2", ChannelId="01", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V2", ChannelId="02", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V2", ChannelId="03", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V2", ChannelId="04", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V2", ChannelId="12", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V2", ChannelId="13", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V2", ChannelId="14", PayPeriodType= PayPeriodType.TenDay },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6V3",CollectionTypeName="超商代收-學雜費", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V3", ChannelId = "01", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V3", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V3", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V3", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V3", ChannelId = "12", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V3", ChannelId = "13", SRange = 1, ERange = 20000, ChannelFee = 0, ChannelFeedBackFee = 0 , ChannelRebateFee = 6 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V3", ChannelId = "14", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V3", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V3", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V3", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V3", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V3", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V3", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V3", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6V4",CollectionTypeName="超商代收-學雜費", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V4", ChannelId = "01", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V4", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V4", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V4", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V4", ChannelId = "12", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 4 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V4", ChannelId = "13", SRange = 1, ERange = 20000, ChannelFee = 0, ChannelFeedBackFee = 0 , ChannelRebateFee = 10 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V4", ChannelId = "14", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 4 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V4", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V4", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V4", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V4", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V4", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V4", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V4", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6V5",CollectionTypeName="超商代收-學雜費", ChargePayType= ChargePayType.Deduction },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V5", ChannelId = "01", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V5", ChannelId = "02", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V5", ChannelId = "03", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V5", ChannelId = "04", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V5", ChannelId = "12", SRange = 20001, ERange = 40000, ChannelFee = 6, ChannelFeedBackFee = 9 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V5", ChannelId = "13", SRange = 20001, ERange = 40000, ChannelFee = 0, ChannelFeedBackFee = 0 , ChannelRebateFee = 15 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V5", ChannelId = "14", SRange = 20001, ERange = 40000, ChannelFee = 6, ChannelFeedBackFee = 9 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V5", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V5", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V5", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V5", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V5", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V5", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V5", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6V6",CollectionTypeName="超商代收-一般", ChargePayType= ChargePayType.Increase },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V6", ChannelId = "01", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V6", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V6", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V6", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V6", ChannelId = "12", SRange = 1, ERange = 20000, ChannelFee = 8, ChannelFeedBackFee = 2 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V6", ChannelId = "13", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V6", ChannelId = "14", SRange = 1, ERange = 20000, ChannelFee = 7, ChannelFeedBackFee = 3 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V6", ChannelId="01", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V6", ChannelId="02", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V6", ChannelId="03", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V6", ChannelId="04", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V6", ChannelId="12", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V6", ChannelId="13", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V6", ChannelId="14", PayPeriodType= PayPeriodType.TenDay },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6V7",CollectionTypeName="超商代收-一般", ChargePayType= ChargePayType.Increase },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V7", ChannelId = "01", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V7", ChannelId = "02", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V7", ChannelId = "03", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V7", ChannelId = "04", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V7", ChannelId = "12", SRange = 20001, ERange = 40000, ChannelFee = 12, ChannelFeedBackFee = 3 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V7", ChannelId = "13", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V7", ChannelId = "14", SRange = 20001, ERange = 40000, ChannelFee = 8, ChannelFeedBackFee = 7 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V7", ChannelId="01", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V7", ChannelId="02", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V7", ChannelId="03", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V7", ChannelId="04", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V7", ChannelId="12", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V7", ChannelId="13", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V7", ChannelId="14", PayPeriodType= PayPeriodType.TenDay },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6V8",CollectionTypeName="超商代收-學雜費", ChargePayType= ChargePayType.Increase },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V8", ChannelId = "01", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V8", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V8", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V8", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V8", ChannelId = "12", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V8", ChannelId = "13", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V8", ChannelId = "14", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V8", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V8", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V8", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V8", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V8", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V8", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V8", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="6V9",CollectionTypeName="超商代收-學雜費", ChargePayType= ChargePayType.Increase},
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V9", ChannelId = "01", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V9", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V9", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V9", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V9", ChannelId = "12", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 4 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V9", ChannelId = "13", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "6V9", ChannelId = "14", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 4 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V9", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V9", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V9", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V9", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V9", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V9", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="6V9", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId=CP.BankCollectionTypeId,CollectionTypeName="銀行通路", ChargePayType= ChargePayType.Increase },
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = CP.BankCollectionTypeId, ChannelId = "00", SRange = 1, ERange = 9999999, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = CP.BankCollectionTypeId, ChannelId = "06", SRange = 1, ERange = 9999999, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = CP.BankCollectionTypeId, ChannelId = "07", SRange = 1, ERange = 9999999, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = CP.BankCollectionTypeId, ChannelId = "A2", SRange = 1, ERange = 9999999, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                //new CollectionTypeDetailModel() {  CollectionTypeId = ConstParameter.BankCollectionTypeId, ChannelId = "A3", SRange = 1, ERange = 9999999, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                //new CollectionTypeDetailModel() {  CollectionTypeId = ConstParameter.BankCollectionTypeId, ChannelId = "A4", SRange = 1, ERange = 9999999, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                //new CollectionTypeDetailModel() {  CollectionTypeId = ConstParameter.BankCollectionTypeId, ChannelId = "A5", SRange = 1, ERange = 9999999, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId=CP.BankCollectionTypeId, ChannelId="00", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId=CP.BankCollectionTypeId, ChannelId="06", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId=CP.BankCollectionTypeId, ChannelId="07", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId=CP.BankCollectionTypeId, ChannelId="A2", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="I0O",CollectionTypeName="超商代收-保險費", ChargePayType= ChargePayType.Deduction},
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "I0O", ChannelId = "01", SRange = 1, ERange = 50000, ChannelFee = 20, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "I0O", ChannelId = "02", SRange = 1, ERange = 50000, ChannelFee = 20, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "I0O", ChannelId = "03", SRange = 1, ERange = 50000, ChannelFee = 20, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "I0O", ChannelId = "04", SRange = 1, ERange = 50000, ChannelFee = 20, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "I0O", ChannelId = "05", SRange = 1, ERange = 50000, ChannelFee = 20, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "I0O", ChannelId = "12", SRange = 1, ERange = 50000, ChannelFee = 9, ChannelFeedBackFee = 11 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "I0O", ChannelId = "13", SRange = 1, ERange = 50000, ChannelFee = 0, ChannelFeedBackFee = 0 , ChannelRebateFee = 20 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "I0O", ChannelId = "14", SRange = 1, ERange = 50000, ChannelFee = 20, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="I0O", ChannelId="01", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="I0O", ChannelId="02", PayPeriodType= PayPeriodType.Week },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="I0O", ChannelId="03", PayPeriodType= PayPeriodType.Week },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="I0O", ChannelId="04", PayPeriodType= PayPeriodType.Week },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="I0O", ChannelId="05", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="I0O", ChannelId="12", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="I0O", ChannelId="13", PayPeriodType= PayPeriodType.TenDay },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="I0O", ChannelId="14", PayPeriodType= PayPeriodType.TenDay },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="R21",CollectionTypeName="國中、小學雜費(現金)", ChargePayType= ChargePayType.Deduction},
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R21", ChannelId = "01", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R21", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R21", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R21", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R21", ChannelId = "12", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R21", ChannelId = "13", SRange = 1, ERange = 20000, ChannelFee = 0, ChannelFeedBackFee = 0 , ChannelRebateFee = 6 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R21", ChannelId = "14", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R21", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R21", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R21", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R21", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R21", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R21", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R21", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="R22",CollectionTypeName="高中、職學雜費(現金)", ChargePayType= ChargePayType.Deduction},
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R22", ChannelId = "01", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R22", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R22", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R22", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R22", ChannelId = "12", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 4 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R22", ChannelId = "13", SRange = 1, ERange = 20000, ChannelFee = 0, ChannelFeedBackFee = 0 , ChannelRebateFee = 10 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R22", ChannelId = "14", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 4 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R22", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R22", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R22", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R22", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R22", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R22", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R22", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="R23",CollectionTypeName="學雜費代收(現金)", ChargePayType= ChargePayType.Deduction},
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R23", ChannelId = "01", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R23", ChannelId = "02", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R23", ChannelId = "03", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R23", ChannelId = "04", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R23", ChannelId = "12", SRange = 20001, ERange = 40000, ChannelFee = 6, ChannelFeedBackFee = 9 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R23", ChannelId = "13", SRange = 20001, ERange = 40000, ChannelFee = 0, ChannelFeedBackFee = 0 , ChannelRebateFee = 15 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R23", ChannelId = "14", SRange = 20001, ERange = 40000, ChannelFee = 6, ChannelFeedBackFee = 9 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R23", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R23", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R23", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R23", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R23", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R23", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R23", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="R24",CollectionTypeName="學雜費代收(現金)", ChargePayType= ChargePayType.Deduction},
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R24", ChannelId = "01", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R24", ChannelId = "02", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R24", ChannelId = "03", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R24", ChannelId = "04", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R24", ChannelId = "12", SRange = 40001, ERange = 60000, ChannelFee = 6, ChannelFeedBackFee = 12 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R24", ChannelId = "13", SRange = 40001, ERange = 60000, ChannelFee = 0, ChannelFeedBackFee = 0 , ChannelRebateFee = 20 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R24", ChannelId = "14", SRange = 40001, ERange = 60000, ChannelFee = 6, ChannelFeedBackFee = 12 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R24", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R24", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R24", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R24", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R24", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R24", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R24", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="R25",CollectionTypeName="國中、小學雜費(現金)", ChargePayType= ChargePayType.Increase},
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R25", ChannelId = "01", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R25", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R25", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R25", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R25", ChannelId = "12", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R25", ChannelId = "13", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R25", ChannelId = "14", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R25", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R25", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R25", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R25", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R25", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R25", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R25", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="R26",CollectionTypeName="高中、職學雜費(現金)", ChargePayType= ChargePayType.Increase},
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R26", ChannelId = "01", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R26", ChannelId = "02", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R26", ChannelId = "03", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R26", ChannelId = "04", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R26", ChannelId = "12", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 4 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R26", ChannelId = "13", SRange = 1, ERange = 20000, ChannelFee = 10, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R26", ChannelId = "14", SRange = 1, ERange = 20000, ChannelFee = 6, ChannelFeedBackFee = 4 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R26", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R26", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R26", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R26", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R26", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R26", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R26", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="R27",CollectionTypeName="學雜費代收(現金)", ChargePayType= ChargePayType.Increase},
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R27", ChannelId = "01", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R27", ChannelId = "02", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R27", ChannelId = "03", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R27", ChannelId = "04", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R27", ChannelId = "12", SRange = 20001, ERange = 40000, ChannelFee = 6, ChannelFeedBackFee = 9 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R27", ChannelId = "13", SRange = 20001, ERange = 40000, ChannelFee = 15, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R27", ChannelId = "14", SRange = 20001, ERange = 40000, ChannelFee = 6, ChannelFeedBackFee = 9 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R27", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R27", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R27", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R27", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R27", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R27", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R27", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                        new CollectionTypeSet() { CollectionType = new CollectionTypeModel() {CollectionTypeId="R28",CollectionTypeName="學雜費代收(現金)", ChargePayType= ChargePayType.Increase},
                            CollectionTypeDetail = new List<CollectionTypeDetailModel>() {
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R28", ChannelId = "01", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R28", ChannelId = "02", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R28", ChannelId = "03", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R28", ChannelId = "04", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R28", ChannelId = "12", SRange = 40001, ERange = 60000, ChannelFee = 6, ChannelFeedBackFee = 12 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R28", ChannelId = "13", SRange = 40001, ERange = 60000, ChannelFee = 18, ChannelFeedBackFee = 0 , ChannelRebateFee = 0 },
                                new CollectionTypeDetailModel() {  CollectionTypeId = "R28", ChannelId = "14", SRange = 40001, ERange = 60000, ChannelFee = 6, ChannelFeedBackFee = 12 , ChannelRebateFee = 0 },
                            },
                            CollectionTypeVerifyPeriod=new List<CollectionTypeVerifyPeriodModel>(){
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R28", ChannelId="01", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R28", ChannelId="02", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R28", ChannelId="03", PayPeriodType= PayPeriodType.NDay_B },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R28", ChannelId="04", PayPeriodType= PayPeriodType.NDay_C },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R28", ChannelId="12", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R28", ChannelId="13", PayPeriodType= PayPeriodType.NDay_A },
                                new CollectionTypeVerifyPeriodModel(){ CollectionTypeId="R28", ChannelId="14", PayPeriodType= PayPeriodType.NDay_A },
                            },
                        },
                    };
                collectionTypes.ForEach(collectionType =>
                {
                    int i = 0;
                    collectionType.CollectionTypeDetail.ForEach(p => { p.RowId = ++i; });
                    if (null == repo.QueryData(new[] { collectionType.CollectionType.CollectionTypeId })) repo.Create(collectionType);
                });
                repo.CommitData(FuncAction.Create);
            }
            finally
            {
                Message.Prefix = string.Empty;
            }
        }
    }
}
